# docker-compose.yml

version: '3.8'

services:
  h2-console:
    build:
      context: .
      dockerfile: Dockerfile.h2
    container_name: h2-console
    ports:
      - "8085:8085"  # Consola Web de H2
      - "9095:9095"  # Servidor TCP de H2
    volumes:
      - ./data:/opt/h2-data  # Persistencia de datos
    environment:
      - H2_OPTIONS=-tcpAllowOthers -webAllowOthers -ifNotExists

  tomcat:
    build:
      context: .
      dockerfile: Dockerfile.tomcat
    container_name: tomcat-server
    ports:
      - "8080:8080"  # Servidor Tomcat
    volumes:
      - ./webapps:/usr/local/tomcat/webapps  # Despliegue de aplicaciones WAR
    depends_on:
      - h2-console






