# Dockerfile.tomcat

# Usar una imagen base de Tomcat con JDK 17 y Temurin
FROM tomcat:9.0.95-jdk17-temurin-jammy

# Eliminar la aplicación web predeterminada (opcional)
RUN rm -rf /usr/local/tomcat/webapps/ROOT

# Copiar el archivo WAR de la aplicación al directorio de webapps de Tomcat
COPY webapps/ROOT.war /usr/local/tomcat/webapps/ROOT.war

# Exponer el puerto 8080
EXPOSE 8080

# Comando para iniciar Tomcat
CMD ["catalina.sh", "run"]


