version: '3.8'

services:
  h2-console:
    build: .  # Indica que Docker debe construir la imagen usando el Dockerfile en el directorio actual
    container_name: h2-console
    ports:
      - "8085:8085"  # Host:Contenedor (Consola Web)
      - "9095:9095"  # Host:Contenedor (Servidor TCP)
    volumes:
      - ./data:/opt/h2-data  # Monta la carpeta local 'data' en el contenedor para persistencia de datos
