version: '3.8'

services:
  spring-boot-app:
    build:
      context: .
    container_name: spring-boot-app
    ports:
      - "8080:8080"  # El puerto en el que la aplicación estará disponible
    volumes:
      - ./target:/app  # Asegúrate de que tu archivo JAR esté en ./target
    networks:
      - umbrella-network

networks:
  umbrella-network:
    driver: bridge
